services:
  - type: web
    name: xeplịch-bvnhigl
    env: python
    buildCommand: ./render-build.sh
    startCommand: python app.py
    plan: free
    envVars:
      - key: DATABASE_URL
        value: <thay bằng URL PostgreSQL do Render cung cấp>
