-- === Bảng chính: timesheet2 ===
CREATE TABLE IF NOT EXISTS public.timesheet2 (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department  VARCHAR(255) NOT NULL,
  start_date  DATE NOT NULL,
  end_date    DATE NOT NULL,
  name        VARCHAR(255) DEFAULT 'Bảng chấm công BHYT',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT timesheet2_date_range_chk CHECK (start_date <= end_date)
);

-- Tối ưu tra cứu theo khoa
CREATE INDEX IF NOT EXISTS ix_timesheet2_department
  ON public.timesheet2(department);

-- === Bảng chi tiết: timesheet2_entry ===
CREATE TABLE IF NOT EXISTS public.timesheet2_entry (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sheet_id  BIGINT NOT NULL,
  user_id   INTEGER NOT NULL,
  work_date DATE NOT NULL,
  code      VARCHAR(50) DEFAULT '',
  deleted   BOOLEAN NOT NULL DEFAULT FALSE,

  -- Khóa ngoại: xóa sheet → xóa luôn entries (khớp cascade ở SQLAlchemy)
  CONSTRAINT fk_t2_entry_sheet
    FOREIGN KEY (sheet_id)
    REFERENCES public.timesheet2(id)
    ON DELETE CASCADE,

  -- FK tới bảng "user" (tên bảng là từ khóa; cần trích dẫn)
  CONSTRAINT fk_t2_entry_user
    FOREIGN KEY (user_id)
    REFERENCES public."user"(id)
    ON DELETE RESTRICT
);

-- Không cho trùng bản ghi theo (sheet, user, ngày)
CREATE UNIQUE INDEX IF NOT EXISTS ux_t2_entry_unique
  ON public.timesheet2_entry(sheet_id, user_id, work_date);

-- Tối ưu lọc theo ngày
CREATE INDEX IF NOT EXISTS ix_t2_entry_work_date
  ON public.timesheet2_entry(work_date);
