"""Thêm location và birth_date vào LeaveRequest

Revision ID: 08ab03e26f3c
Revises: df7dbdf86230
Create Date: 2025-06-29 21:07:24.925275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ab03e26f3c'
down_revision = 'df7dbdf86230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kip_configuration')
    op.drop_table('kip')
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('birth_date')
        batch_op.drop_column('location')

    op.create_table('kip',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('doctor_id', sa.INTEGER(), nullable=True),
    sa.Column('nurse1_id', sa.INTEGER(), nullable=True),
    sa.Column('nurse2_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['nurse1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['nurse2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kip_configuration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), nullable=False),
    sa.Column('num_shifts', sa.INTEGER(), nullable=True),
    sa.Column('kips_per_shift', sa.INTEGER(), nullable=True),
    sa.Column('doctors_per_kip', sa.INTEGER(), nullable=True),
    sa.Column('nurses_per_kip', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
