"""Add ChamCong model

Revision ID: 2c6328c029fa
Revises: 96b57a7c37d0
Create Date: 2025-07-17 22:03:39.239159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6328c029fa'
down_revision = '96b57a7c37d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cham_cong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hazard_config', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('duration_hours',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hazard_config', schema=None) as batch_op:
        batch_op.alter_column('duration_hours',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    op.drop_table('cham_cong')
    # ### end Alembic commands ###
