"""Add position to hazard_config

Revision ID: 636280ec95e1
Revises: 2c6328c029fa
Create Date: 2025-07-22 11:36:12.415815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636280ec95e1'
down_revision = '2c6328c029fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_setting')
    with op.batch_alter_table('hazard_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hazard_config', schema=None) as batch_op:
        batch_op.drop_column('position')

    op.create_table('department_setting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=True),
    sa.Column('value', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department')
    )
    # ### end Alembic commands ###
