"""Add active column to User

Revision ID: 96b57a7c37d0
Revises: ece9c8b00af4
Create Date: 2025-07-16 11:48:25.598057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b57a7c37d0'
down_revision = 'ece9c8b00af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holiday')
    op.drop_table('department_setting')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    op.create_table('department_setting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('max_people_per_day', sa.INTEGER(), nullable=True),
    sa.Column('num_shifts', sa.INTEGER(), nullable=True),
    sa.Column('cas_per_shift', sa.INTEGER(), nullable=True),
    sa.Column('doctors_per_ca', sa.INTEGER(), nullable=True),
    sa.Column('nurses_per_ca', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('holiday',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###
