"""add start_year and signature_file to user

Revision ID: d30d0fdfffee
Revises: 636280ec95e1
Create Date: 2025-08-28 20:17:08.295035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30d0fdfffee'
down_revision = '636280ec95e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_setting')
    op.drop_table('leave')
    with op.batch_alter_table('hazard_config', schema=None) as batch_op:
        batch_op.alter_column('machine_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('machine_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_order'), ['order'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('signature_file',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('email')

    with op.batch_alter_table('user_machine_hazard', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_machine_hazard', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.alter_column('signature_file',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_order'))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('machine_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('hazard_config', schema=None) as batch_op:
        batch_op.alter_column('machine_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('leave',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_setting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=True),
    sa.Column('value', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department')
    )
    # ### end Alembic commands ###
