"""Add kip and kip configuration

Revision ID: df7dbdf86230
Revises: 
Create Date: 2025-06-19 17:02:09.071436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7dbdf86230'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kip_configuration', schema=None) as batch_op:
        batch_op.alter_column('num_shifts',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('kips_per_shift',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kip_configuration', schema=None) as batch_op:
        batch_op.alter_column('kips_per_shift',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('num_shifts',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
